const GET_PROJECTS_SAGA = 'GET_PROJECTS_SAGA';
const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';
const ADD_TASK_SAGA = 'ADD_TASK_SAGA';
const UPDATE_TASK_SAGA = 'UPDATE_TASK_SAGA';
const SET_PROJECTS = 'SET_PROJECTS';
const SET_PROJECT = 'SET_PROJECT';
const SET_TASK = 'SET_TASK';
const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
const REQUEST_ERROR = 'REQUEST_ERROR';
const CREATE_PROJECT = 'CREATE_PROJECT';
const UPDATE_PROJECT_STATUS = 'UPDATE_PROJECT_STATUS';
const SET_TASKS = 'SET_TASKS';

export {  
  GET_PROJECTS_SAGA,
  CREATE_PROJECT_SAGA,
  DELETE_PROJECT_SAGA,
  ADD_TASK_SAGA,
  UPDATE_TASK_SAGA,
  SET_PROJECTS,
  SET_PROJECT,
  SET_TASK,
  REQUEST_SUCCESS,
  REQUEST_ERROR,
  CREATE_PROJECT,
  UPDATE_PROJECT_STATUS,
  SET_TASKS,
};
